### ISSUE TITLE
Trouble navigating interactive mode on Windows

### ISSUE THREAD

**Issue by caycaycarly** [mithrandie/csvq#26] opened 2020-01-31 03:44 UTC
I couldn't use csvq in interactive mode on git-bash because it isn't a real shell, so I went ahead and ran it on powershell.

But I ran into a few problems, like...

[Some of these problems seem really weird and I hope it might be isolated to just my computer, but looking for a confirmation]

1> Navigating using the arrow keys. Going backwards is not possible without using backspace.
2> Typing single or double quotes autocompleted the closing quote and I couldn't navigate my cursor out of the quote without deleting the closing quote using Ctrl+D and manually closing it myself later.
3> Not being able to run the previous command run in the interactive mode using the up arrow key

**Comment by mithrandie** [comment] 2020-01-31 04:07
Let me check the behavior later. It may take a few days.

**Comment by mithrandie** [comment] 2020-02-03 08:54
@caycaycarly 

I checked the behavior on Windows.
Certainly the arrow keys are not working on Windows.

As a workaround, the following shortcut keys can be used instead of the arrow keys.

- Ctrl+B (Backward one character)
- Ctrl+F (Forward one character)
- Ctrl+P (Previous Line)
- Ctrl+N (Next Line)

See this page for available shortcut keys.
https://github.com/chzyer/readline/blob/master/doc/shortcut.md


The interactive shell uses an external library, so I don't know if it can be fixed soon.
I'll investigate the cause anyway.

**Comment by mithrandie** [comment] 2020-02-04 15:06
This bug has been fixed and the fix is released as version 1.12.4.
Thank you for reporting.

**Closed by mithrandie** 2020-02-04 15:06 UTC
Labels: bug
